// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjErFyPQ9T99gITIebOJyJ2zAaIv3P1x4',
    appId: '1:241077366604:web:e8f45669652479993c69e9',
    messagingSenderId: '241077366604',
    projectId: 'flutter-firebase-2b53c',
    authDomain: 'flutter-firebase-2b53c.firebaseapp.com',
    storageBucket: 'flutter-firebase-2b53c.appspot.com',
    measurementId: 'G-3MDYRTFR4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgzhZkWDbBbYq0qJ7jXP9K9WxUqrd8-JA',
    appId: '1:241077366604:android:078b03ab66bb51913c69e9',
    messagingSenderId: '241077366604',
    projectId: 'flutter-firebase-2b53c',
    storageBucket: 'flutter-firebase-2b53c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMe6E--W6tI-1uKsqEjd2VMjBIuf4xhGE',
    appId: '1:241077366604:ios:617b0ef5abd388c73c69e9',
    messagingSenderId: '241077366604',
    projectId: 'flutter-firebase-2b53c',
    storageBucket: 'flutter-firebase-2b53c.appspot.com',
    iosClientId: '241077366604-tshoql3n7vmk7fqvol8ad0a9ncvhnq40.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentCommunication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMe6E--W6tI-1uKsqEjd2VMjBIuf4xhGE',
    appId: '1:241077366604:ios:617b0ef5abd388c73c69e9',
    messagingSenderId: '241077366604',
    projectId: 'flutter-firebase-2b53c',
    storageBucket: 'flutter-firebase-2b53c.appspot.com',
    iosClientId: '241077366604-tshoql3n7vmk7fqvol8ad0a9ncvhnq40.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentCommunication',
  );
}
